#!/bin/bash
HOUR=$(date +%k)

if [ $HOUR -gt 18 ] || [ $HOUR -lt 5 ] ; then
	cat /home/isaac/.config/kitty/kitty_dark.conf > /home/isaac/.config/kitty/kitty.conf
	kitty @set-colors /home/isaac/.config/kitty/kitty-themes/themes/OceanicMaterial.conf
else
	cat /home/isaac/.config/kitty/kitty_light.conf > /home/isaac/.config/kitty/kitty.conf
	kitty @set-colors /home/isaac/.config/kitty/kitty-themes/themes/Solarized_Light.conf
fi

