#!/bin/bash
HOUR=$(date +%k)

while true
do
    if [ $HOUR -gt 18 ] || [ $HOUR -lt 5 ] ; then
        conky -c ~/.config/conky/conkyrc_top_dark
        conky -c ~/.config/conky/conkyrc_bottom_dark
        feh --bg-scale ~/wallpapers/debian_dark.png
    else
        conky -c ~/.config/conky/conkyrc_top_light
        conky -c ~/.config/conky/conkyrc_bottom_light
        feh --bg-scale ~/wallpapers/debian_light.png
    fi
    sleep 1200
    killall -9 conky
done

