#!/bin/bash

HOUR=$(date +%k)

if [ $HOUR -ge 18 ] || [ $HOUR -le 4 ]; then
	echo "font_family     	JetBrains Mono NL
font_size 		13
bold_font		auto
italic_font		auto
bold_italic_font	auto
allow_remote_control yes" > /home/isaac/.config/kitty/kitty.conf
	kitty @ set-colors -a -c "$HOME/.config/kitty/kitty-themes/themes/OceanicMaterial.conf"

else
	echo "font_family     	JetBrains Mono NL
font_size 		13
bold_font		auto
italic_font		auto
bold_italic_font	auto
allow_remote_control 	yes" > /home/isaac/.config/kitty/kitty.conf
	kitty @ set-colors -a -c "$HOME/.config/kitty/kitty-themes/themes/PencilLight.conf"
fi

